spring:

  datasource:
    url: jdbc:mysql://192.168.1.146:3306/zzyy?serverTimezone=Asia/Shanghai
    username: root
    password: aaaa
    driver-class-name: com.mysql.cj.jdbc.Driver


  freemarker:
    request-context-attribute: ctx
    template-loader-path: classpath:/templates
    suffix: .ftl
    settings:
      classic_compatible: true

  #自定义静态资源
  mvc:
    # put delete
    hiddenmethod:
      filter:
        enabled: true
    #静态文件访问配置
    static-path-pattern: /static/**

server:
  port: 8888

